# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
    max-http-post-size: 31457280
  port: 8080
  connection-timeout: 5000
  context-path: /lt-web


spring:
  profiles:
    active: dev


